export const createURL = (url, params) => {
	const newURL = new URL(url);

	Object.keys(params).map((key) => newURL.searchParams.set(key, params[key]));

	return newURL;
};

export const createRelativeURL = (url, params) => {
	const newURL = new URL(window.location.origin + url);

	Object.keys(params).map((key) => newURL.searchParams.set(key, params[key]));

	return newURL;
};

export const generateUsername = () => {
	const randomElement = (arr) => arr[Math.floor(Math.random() * arr.length)];

	const adjectives = ['Happy', 'Bright', 'Shiny', 'Mighty'];
	const adj = randomElement(adjectives);

	const animals = ['Dog', 'Cow', 'Parrot', 'Cat'];
	const animal = randomElement(animals);

	const number = Math.random().toFixed(1).toString().substring(2);

	return `${adj}${animal}${number}`;
};

export const setCookie = (cookie) => {
	if (!cookie) return;

	document.cookie = cookie;
};

export const getCookie = (name) => {
	const cookies = document.cookie.split('; ');

	const result = cookies.filter(
		(nameValue) => nameValue.split('=')[0] === name
	);

	if (!result.length) return null;

	return result[0].split('=')[1];
};

export const _generateUsername = () => {
	// const adjectives = [
	// 	'Able ',
	// 	'Absent ',
	// 	'All',
	// 	'Afraid',
	// 	'Alive',
	// 	'Angry',
	// 	'Another',
	// 	'Asleep',
	// 	'Average',
	// 	'Away',
	// 	'Back',
	// 	'Bad',
	// 	'Basic',
	// 	'Beautiful',
	// 	'Best',
	// 	'Big',
	// 	'Bold',
	// 	'Boring',
	// 	'Bright',
	// 	'Calm',
	// 	'Careful',
	// 	'Cheap',
	// 	'Clean',
	// 	'Close',
	// 	'Cloudy',
	// 	'Closed',
	// 	'Cold',
	// 	'Common',
	// 	'Confident',
	// 	'Curious',
	// 	'Current',
	// 	'Cute',
	// 	'Dangerous',
	// 	'Dark',
	// 	'Dead',
	// 	'Decent',
	// 	'Different',
	// 	'Dirty',
	// 	'Down',
	// 	'Dry',
	// 	'Due',
	// 	'Dull',
	// 	'Early',
	// 	'Economic',
	// 	'Economical',
	// 	'Efficient',
	// 	'Exciting',
	// 	'Expected',
	// 	'Expensive',
	// 	'Even',
	// 	'Famous',
	// 	'Far',
	// 	'Fair',
	// 	'Fast',
	// 	'Fat',
	// 	'Financial',
	// 	'Firm',
	// 	'First',
	// 	'Foreign',
	// 	'Full',
	// 	'Funny',
	// 	'Further / farther',
	// 	'Future',
	// 	'Former',
	// 	'Free',
	// 	'Friendly',
	// 	'General',
	// 	'Generous',
	// 	'Genuine',
	// 	'Good',
	// 	'Great',
	// 	'Guilty',
	// 	'Handsome',
	// 	'Half',
	// 	'Happy',
	// 	'Hard',
	// 	'Healthy',
	// 	'Heavy',
	// 	'Helpful',
	// 	'High',
	// 	'Hot',
	// 	'Huge',
	// 	'Hungry',
	// 	'Important',
	// 	'Inner',
	// 	'Innocent',
	// 	'Intelligent',
	// 	'Interesting',
	// 	'Just',
	// 	'Kind',
	// 	'Large',
	// 	'Last',
	// 	'Late',
	// 	'Later',
	// 	'Lazy',
	// 	'Left',
	// 	'Light',
	// 	'Like',
	// 	'Likely',
	// 	'Little',
	// 	'Local',
	// 	'Lonely',
	// 	'Long',
	// 	'Loud',
	// 	'Low',
	// 	'Lucky',
	// 	'Mad',
	// 	'Main',
	// 	'National',
	// 	'Natural',
	// 	'Near',
	// 	'Nervous',
	// 	'New',
	// 	'Next',
	// 	'Nice',
	// 	'Noisy',
	// 	'Obvious',
	// 	'Odd',
	// 	'Official',
	// 	'Old',
	// 	'Only',
	// 	'Open',
	// 	'Other',
	// 	'Outer',
	// 	'Over',
	// 	'Own',
	// 	'Particular',
	// 	'Perfect',
	// 	'Pleasant',
	// 	'Polite',
	// 	'Political',
	// 	'Popular',
	// 	'Poor',
	// 	'Possible',
	// 	'Present',
	// 	'Private',
	// 	'Proud ',
	// 	'Public',
	// 	'Pure',
	// 	'Quick',
	// 	'Quiet',
	// 	'Rare',
	// 	'Real',
	// 	'Reasonable',
	// 	'Recent',
	// 	'Rich',
	// 	'Right',
	// 	'Round',
	// 	'Running',
	// 	'Safe',
	// 	'Same',
	// 	'Scary',
	// 	'Second',
	// 	'Selfish',
	// 	'Serious',
	// 	'Sharp',
	// 	'Short',
	// 	'Shy',
	// 	'Sick',
	// 	'Similar',
	// 	'Slim',
	// 	'Slow',
	// 	'Small',
	// 	'Smart',
	// 	'Smelly',
	// 	'Smooth',
	// 	'Soft',
	// 	'Special',
	// 	'Square',
	// 	'Still',
	// 	'Strong',
	// 	'Stupid',
	// 	'Sunny',
	// 	'Sure',
	// 	'Tall',
	// 	'Tasty',
	// 	'Thick',
	// 	'Thin',
	// 	'Thirsty',
	// 	'Tiny',
	// 	'Top',
	// 	'Total',
	// 	'True',
	// 	'Ugly',
	// 	'Unusual',
	// 	'Used',
	// 	'Useful',
	// 	'Useless',
	// 	'Vague',
	// 	'Violent',
	// 	'Warm',
	// 	'Weak',
	// 	'Weird',
	// 	'Well',
	// 	'Wet',
	// 	'Whole',
	// 	'Wild',
	// 	'Wonderful',
	// 	'Working',
	// 	'Wrong',
	// 	'Young',
	// ];
	// const animals = [
	// 	'Dog',
	// 	'Puppy',
	// 	'Turtle',
	// 	'Rabbit',
	// 	'Parrot',
	// 	'Cat',
	// 	'Kitten',
	// 	'Goldfish',
	// 	'Mouse',
	// 	'Tropical fish',
	// 	'Hamster',
	// 	'Cow',
	// 	'Rabbit',
	// 	'Ducks',
	// 	'Shrimp',
	// 	'Pig',
	// 	'Goat',
	// 	'Crab',
	// 	'Deer',
	// 	'Bee',
	// 	'Sheep',
	// 	'Fish',
	// 	'Turkey',
	// 	'Dove',
	// 	'Chicken',
	// 	'Horse',
	// 	'Crow',
	// 	'Peacock',
	// 	'Dove',
	// 	'Sparrow',
	// 	'Goose',
	// 	'Stork',
	// 	'Pigeon',
	// 	'Turkey',
	// 	'Hawk',
	// 	'Bald eagle',
	// 	'Raven',
	// 	'Parrot',
	// 	'Flamingo',
	// 	'Seagull',
	// 	'Ostrich',
	// 	'Swallow',
	// 	'Black bird',
	// 	'Penguin',
	// 	'Robin',
	// 	'Swan',
	// 	'Owl',
	// 	'Woodpecker',
	// 	'Squirrel',
	// 	'Dog',
	// 	'Chimpanzee',
	// 	'Ox',
	// 	'Lion',
	// 	'Panda',
	// 	'Walrus',
	// 	'Otter',
	// 	'Mouse',
	// 	'Kangaroo',
	// 	'Goat',
	// 	'Horse',
	// 	'Monkey',
	// 	'Cow',
	// 	'Koala',
	// 	'Mole',
	// 	'Elephant',
	// 	'Leopard',
	// 	'Hippopotamus',
	// 	'Giraffe',
	// 	'Fox',
	// 	'Coyote',
	// 	'Hedgehong',
	// 	'Sheep',
	// 	'Deer',
	// 	'Giraffe',
	// 	'Woodpecker',
	// 	'Camel',
	// 	'Starfish',
	// 	'Koala',
	// 	'Alligator',
	// 	'Owl',
	// 	'Tiger',
	// 	'Bear',
	// 	'Blue whale',
	// 	'Coyote',
	// 	'Chimpanzee',
	// 	'Raccoon',
	// 	'Lion',
	// 	'Arctic wolf',
	// 	'Crocodile',
	// 	'Dolphin',
	// 	'Elephant',
	// 	'Squirrel',
	// 	'Snake',
	// 	'Kangaroo',
	// 	'Hippopotamus',
	// 	'Elk',
	// 	'Fox',
	// 	'Gorilla',
	// 	'Bat',
	// 	'Hare',
	// 	'Toad',
	// 	'Frog',
	// 	'Deer',
	// 	'Rat',
	// 	'Badger',
	// 	'Lizard',
	// 	'Mole',
	// 	'Hedgehog',
	// 	'Otter',
	// 	'Reindeer',
	// 	'Crab',
	// 	'Fish',
	// 	'Seal',
	// 	'Octopus',
	// 	'Shark',
	// 	'Seahorse',
	// 	'Walrus',
	// 	'Starfish',
	// 	'Whale',
	// 	'Penguin',
	// 	'Jellyfish',
	// 	'Squid',
	// 	'Lobster',
	// 	'Pelican',
	// 	'Clams',
	// 	'Seagull',
	// 	'Dolphin',
	// 	'Shells',
	// 	'Sea urchin',
	// 	'Cormorant',
	// 	'Otter',
	// 	'Pelican',
	// 	'Sea anemone',
	// 	'Sea turtle',
	// 	'Sea lion',
	// 	'Coral',
	// 	'Moth',
	// 	'Bee',
	// 	'Butterfly',
	// 	'Spider',
	// 	'Ant',
	// 	'Dragonfly',
	// 	'Fly',
	// 	'Mosquito',
	// 	'Grasshopper',
	// 	'Beetle',
	// 	'Cockroach',
	// 	'Centipede',
	// 	'Worm',
	// 	'Louse',
	// ];
	// const number = 59;
};
